AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Optional s3 Bucket to be used for experso

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
  
  SampleBucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref S3Bucket
      PolicyDocument: 
        Statement:
          - Effect: Allow
            Principal:
              Service: personalize.amazonaws.com
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
          - Effect: Allow
            Principal:
              Service: personalize.amazonaws.com
            Action: 's3:ListBucket'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
          - 
            Action: 
              - "s3:ListBucket"
            Effect: "Allow"
            Resource: 
              Fn::Join: 
                - ""
                - 
                  - "arn:aws:s3:::"
                  - 
                    Ref: "S3Bucket"
            Principal:
              Service: personalize.amazonaws.com
Outputs:
  s3BucketName:
    Description: The S3 bucket name
    Value: !Ref S3Bucket
