version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tv2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-iq67aiu1indy"
s3_prefix = "tv2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SNSTopicName=luistv2 SubscriptionEmail=lopez470@umn.edu CampaignArn=luisv2"
