version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "step-f-v2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-iq67aiu1indy"
s3_prefix = "step-f-v2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Email=\"lopez470@umn.edu\" ParameterFile=\"params.json\""
